### ISSUE TITLE
Issue calculating LOS using points / corners

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-token-visibility#14]
See https://ptb.discord.com/channels/170995199584108546/513918036919713802/1047674279032004618

![image](https://user-images.githubusercontent.com/1267134/204946546-b868a99a-3eac-467b-9ec8-a6d356905d3c.png)

Large token should be able to see small token from bottom left corner?

**Comment by Zamrod** [comment]
So for more information about this, here's what I'd LIKE to see happen: Anything that you wouldn't have full cover against in the 5e rules you should be able to see as well.

In theory, this means that you calculate line of sight from every corner of every square that you occupy and then combine the area of all of that LOS together. I believe that would slow down the game too much with all the extra calculations. I think that you could likely do it practically with only 5 points: Middle and the for corners of the creature's token. If you do so, you'd see quite a bit more area:

![image](https://user-images.githubusercontent.com/12570777/206842896-58d11d32-e8f9-424d-ad8e-4a24ab038465.png)

This means that a token in the location of the X could be almost completely seen and they'd only have 1/2 cover.

At the moment there's no way using the module or core for either of those tokens to see each other because they only measure line of sight from the center of each token.

**Comment by caewok** [comment]
v0.6.0 will allow you to measure line-of-sight from multiple points on the viewer. I think that will address this issue. In addition, v0.6.0 will split out cover into a separate module so that you can decide whether cover should use the same rules as vision. So I am closing this for now as "soon-to-be-resolved." Thanks!
