### ISSUE TITLE
Tokens give full cover with 3D algorithm

### ISSUE THREAD

**Issue by gurgugnao** [caewok/fvtt-token-visibility#30]
Hi! Thank you for your great work! I noticed that tokens give full cover with 3D algorithm when, as per D&D5e rule (PH pg. 196), they should give just half cover. Can you fix it or add an option to decide how much cover they give? Thanks!

![Token cover 3D](https://user-images.githubusercontent.com/122090327/210990597-ce2020af-fc1d-4e47-a951-58241fbf25ae.jpg)

**Comment by caewok** [comment]
Thanks!

I think PHB p. 196 is a bit vague on this point. The first part says, "For example, if a target is behind a creature that gives half cover ...." To me, that is saying that a creature *might* give half cover, not that every creature gives half cover. But I do get what you are saying, that the later example in that paragraph says "The obstacle might be a . . . creature, whether that creature is an enemy or a friend." This seems to imply that creatures are only supposed to provide half cover, but it is obvious that a more realistic approach would consider relative heights before setting cover.

Here is the technical problem, though: I don't have any basis to change the size or shape of the live token, and it is the shape of the 3d token that is used to measure cover. And the PHB and DMG don't give any suggestions for how such a thing would be measured. So tokens, for purposes of Area3d, are approximated as cubes. (Or, for hexes, sort of lumpy cylinders based on the hex shape.) 

Now, if you are using midi-qol, there is an option in the Alt Token Visibility settings that allows the GM to intervene. Basically, a dialog pops up when it detects cover, and the GM can change the cover to be applied. If you are not using automation, then the GM can simply overrule. 

Otherwise, I see two possible solutions: 
1. Use 3d tokens with exact token shapes. This would naturally mean that any given token is very unlikely to provide full cover to another, assuming similarly sized tokens. But this would be very difficult, as it would require moving everything to the GPU as well as importing and using 3d shape objects created elsewhere. Ripper's 3d Canvas can do this, but I doubt I will take this on. 
2. Allow tokens to "duck" or "crouch." This would give a reason to make a live token half-height, like what is assumed for dead tokens. I will look into this, but my initial take is that setting the prone condition in dnd5e would suffice. Then the cover algorithm could optionally take the token's condition into account, and adjust height accordingly. I will keep this open and look into this possibility at some point.

**Comment by gurgugnao** [comment]
Thank you for the answer. I think solution number 2 (with an option) is the best. Setting live token as half-height and, if prone condition is enabled, to 1/4 height or 0 height. Thus, with this hypothetical option enabled, dead token would be treated as live prone token.

Also, as per PHB. pg 196: "If a target is behind multiple sources of cover, only the most protective degree of cover applies; the degrees aren't added together. For example, if a target is behind a creature that gives half cover and a tree trunk that gives three­quarters cover, the target has three-quarters cover.
Now, the behaviour is to add cover degrees:
![Multiple cover (1)](https://user-images.githubusercontent.com/122090327/211165697-2ce036e8-3f92-4bb9-ad14-f635a8fa9e09.JPG)
![Multiple cover (2)](https://user-images.githubusercontent.com/122090327/211165699-8c728683-5a00-4c98-a7bd-42c243035ee0.JPG)

**Comment by caewok** [comment]
Addressed in v0.4.4. Thanks!
