### ISSUE TITLE
[PF2e] 0.4.2 Token not providing cover

### ISSUE THREAD

**Issue by jocolamarco** [caewok/fvtt-token-visibility#36]
Config:

![image](https://user-images.githubusercontent.com/45291719/215791109-7c13dee9-4be0-403c-b127-bd0d3d9c4ad6.png)

Video of issue:

[cover issue.webm](https://user-images.githubusercontent.com/45291719/215791699-351cdcf4-8ad1-4c6f-8ffa-9a20d56f3cbf.webm)

**Comment by MS-PBS** [comment]
I have this issue in PF2e 4.9.3, Foundry ver 10 b 291, and ATV 0.4.3

**Comment by Janonas** [comment]
The cover setting from this module just straight up dont work, which is a bit strange, since pf2e has its own cover conditions.

**Comment by caewok** [comment]
Is this still an issue in v0.4.4?

**Comment by caewok** [comment]
Fixed in v0.4.5. As for PF2e cover effects, the last time I looked at them, I could not figure out a viable way to assign them correctly. Plus PF2e has fewer hooks than dnd5e, which makes it difficult or impossible to mess with the combat workflow. But I intend to take another run at better integrating with PF2e cover effects.
