### ISSUE TITLE
Live token cover set to flat but still problematic

### ISSUE THREAD

**Issue by MotoMoto1234** [caewok/fvtt-token-visibility#66]
It seems the percentage of cover on adjacent tokens is set too high or something, I would not rule the coverage this narrow for cover:

[adjacent token cover issue.webm](https://github.com/caewok/fvtt-token-visibility/assets/116308065/3a8d09a1-bf70-40a3-9f15-6b2802c47591)

The clip has the side effect of the drag ruler not snapping so its a lil misleading but it still visible here.  It feels like the non cover token spread should be 1 more token out when comparing cover:

![image](https://github.com/caewok/fvtt-token-visibility/assets/116308065/f3bfbc2d-f1bc-416d-88d9-6875a32deb43)

**Comment by MotoMoto1234** [comment]
Heres the extreme example:

![image](https://github.com/caewok/fvtt-token-visibility/assets/116308065/466c70a2-26df-416b-8e13-f0a9a4bbc166)


And to confirm its not tactical grid shennanigans:

![image](https://github.com/caewok/fvtt-token-visibility/assets/116308065/ebd18b49-8d79-4e58-8cbb-0d4c80057b86)

**Comment by MotoMoto1234** [comment]
If you have a combination of settings that could fix this let me know I've pretty much tried every combo.

**Comment by caewok** [comment]
This appears to be working as expected. I see what you mean, but not sure I completely agree that no one should have cover in a tight formation like this. 

If you use only the center point of the target to calculate cover, that would mostly address this. 

For the upcoming v0.6.0, there is an option to use front-facing corners only in the Points algorithm. I think that would address this issue. 

For other points options and for the Area3d algorithm, I don't see a great solution. I could add a toggle to ignore "adjacent" tokens, but under what conditions? Presumably you would consider a token to have cover if it is directly behind another token. So how do I know when a token should be considered to no longer provide cover? Keep in mind that this line formation could be diagonal or otherwise staggered, and we would want a consistent result as the line formation rotates.

**Comment by caewok** [comment]
Mostly addressed in v0.6 series. But see issue #77.
