### ISSUE TITLE
Token Scale throws off cover calc

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-token-visibility#69]
If a token is scaled it will throw off the cover calc. For instance, using FA Tokens, which are often scaled to 3x for visual effects, makes ATV think the actual creature is VERY BIG and thus, it's not afforded the correct cover. 

Example: An orc war priest, which is medium sized, has. FA token that is set to be scaled at 3x. Its computed height is 15 feet, and thus, intervening tokens don't give cover.

Normal 1x scale:
![image](https://github.com/caewok/fvtt-token-visibility/assets/4516034/ad15e450-87e1-4904-aaf7-a0c67e3f46ac)

3x scale:
![image](https://github.com/caewok/fvtt-token-visibility/assets/4516034/5477f8b0-07c0-46b9-ae9c-8122bd3615d1)

3x token scale. you can see the intervening tokens don't give cover as they should
![CleanShot_2023-11-08_at_16 49 58](https://github.com/caewok/fvtt-token-visibility/assets/4516034/19e51110-02d3-46a9-aa43-debcef0b8b22)

Back to 1x scale and all works ok
![CleanShot_2023-11-08_at_16 51 26](https://github.com/caewok/fvtt-token-visibility/assets/4516034/f0e1f910-2508-4d88-83d0-8d901791f563)

**Comment by ctbritt** [comment]
Seems to be related to Wall Height somehow. If I set the height of the token manually, it works ok.

**Comment by caewok** [comment]
That's not really a bug. It is correctly determining that a 15' token does not get the same cover as a 5' token. It uses scaling to determine this because the `Wall Height` module has long used scaling to determine height. As you noted, you can manually set the height of the token to overcome this.

Using "medium sized" is very problematic, because that is system-specific. I am not saying that basing token height on scaling is ideal, however. Ultimately, I would prefer to see Foundry add a `token height` parameter that systems could then modify as makes sense for each system. For dnd5e, that would likely be based on creature size.

I will close this and add a new feature request to ignore `Wall Height` and instead use system-specific sizing. Not promising I will do this soon, but I understand the confusion here.
